export type CompanyOption = {
  label: string;
  value: string;
};

export const COMPANY_OPTIONS: CompanyOption[] = [
  { label: "Accenture", value: "Accenture" },
  { label: "Adobe", value: "adobe" },
  { label: "American Express", value: "american express" },
  { label: "Apple", value: "apple" },
  { label: "Bain & Company", value: "bain company" },
  { label: "Bain Consulting Group", value: "Bain Consulting Group" },
  { label: "Barclays", value: "barclays" },
  { label: "Bloomberg", value: "bloomberg" },
  { label: "Booz Allen Hamilton", value: "Booz Allen Hamilton" },
  { label: "Capgemini", value: "capgemini" },
  { label: "Cisco", value: "cisco" },
  { label: "Cognizant", value: "cognizant" },
  { label: "Crew Carwash", value: "crew carwash" },
  { label: "Deloitte", value: "Deloitte" },
  { label: "Delta", value: "delta" },
  { label: "EPAM Systems", value: "epam systems" },
  { label: "Ericsson", value: "ericsson" },
  { label: "Ernst & Young (EY)", value: "EY" },
  { label: "Fidelity Investments", value: "fidelity investments" },
  { label: "General Electric (GE)", value: "ge" },
  { label: "Google", value: "Google" },
  { label: "H-E-B", value: "heb" },
  { label: "Hewlett Packard Enterprise (HPE)", value: "HPE" },
  { label: "Houston Methodist", value: "houston methodist" },
  { label: "In-N-Out", value: "in n out" },
  { label: "Intuit", value: "intuit" },
  { label: "Jacobs", value: "jacobs" },
  { label: "Johnson & Johnson", value: "johnson and johnson" },
  { label: "Keller Williams", value: "keller williams" },
  { label: "KPMG", value: "KPMG" },
  { label: "Lockheed Martin", value: "lockheed martin" },
  { label: "Lululemon", value: "lululemon" },
  { label: "Mars", value: "mars" },
  { label: "Mastercard", value: "mastercard" },
  { label: "McKinsey", value: "McKinsey" },
  { label: "Microsoft", value: "microsoft" },
  { label: "Nike", value: "nike" },
  { label: "Nokia", value: "nokia" },
  { label: "NVIDIA", value: "nvidia" },
  { label: "Optum", value: "Optum" },
  { label: "PricewaterhouseCoopers (PwC)", value: "pwc" },
  { label: "Royal Bank of Canada (RBC)", value: "rbc" },
  { label: "Ryan", value: "ryan" },
  { label: "SAP", value: "sap" },
  { label: "ServiceNow", value: "service now" },
  { label: "Siemens", value: "siemens" },
  { label: "Tata Consultancy Services (TCS)", value: "TCS" },
  { label: "TC2S", value: "tc2s" },
  { label: "Thomson Reuters", value: "thomson reuters" },
  { label: "TP", value: "tp" },
  { label: "Unilever", value: "unilever" },
];
